### ISSUE TITLE
Please consider renaming this to something less generic

### ISSUE THREAD

**Issue by unixorn** [Abdalla981/zsh_theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name **zsh-theme** is very generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by Abdalla981** [comment]
Thank you for reaching out. I did change the name. Please let me know if there's any more issue.
