### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Abdalla981/zsh_theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Abdalla981** [comment]
Thank you for reaching out. I added a license file. Please let me know if there are any more issues.
